export const RESTAURANTS_LIST_REQUEST = 'RESTAURANTS_LIST_REQUEST'
export const RESTAURANTS_LIST_SUCCESS = 'RESTAURANTS_LIST_SUCCESS'
export const RESTAURANTS_LIST_FAIL = 'RESTAURANTS_LIST_FAIL'

export const RESTAURANTS_DETAILS_REQUEST = 'RESTAURANTS_DETAILS_REQUEST'
export const RESTAURANTS_DETAILS_SUCCESS = 'RESTAURANTS_DETAILS_SUCCESS'
export const RESTAURANTS_DETAILS_FAIL = 'RESTAURANTS_DETAILS_FAIL'

export const RESTAURANTS_DELETE_REQUEST = 'RESTAURANTS_DELETE_REQUEST'
export const RESTAURANTS_DELETE_SUCCESS = 'RESTAURANTS_DELETE_SUCCESS'
export const RESTAURANTS_DELETE_FAIL = 'RESTAURANTS_DELETE_FAIL'
export const RESTAURANTS_DELETE_RESET = 'RESTAURANTS_DELETE_RESET'

export const RESTAURANTS_CREATE_REQUEST = 'RESTAURANTS_CREATE_REQUEST'
export const RESTAURANTS_CREATE_SUCCESS = 'RESTAURANTS_CREATE_SUCCESS'
export const RESTAURANTS_CREATE_FAIL = 'RESTAURANTS_CREATE_FAIL'
export const RESTAURANTS_CREATE_RESET = 'RESTAURANTS_CREATE_RESET'

export const RESTAURANTS_UPDATE_REQUEST = 'RESTAURANTS_UPDATE_REQUEST'
export const RESTAURANTS_UPDATE_SUCCESS = 'RESTAURANTS_UPDATE_SUCCESS'
export const RESTAURANTS_UPDATE_FAIL = 'RESTAURANTS_UPDATE_FAIL'
export const RESTAURANTS_UPDATE_RESET = 'RESTAURANTS_UPDATE_RESET'

export const REVIEWS_CREATE_REQUEST = 'REVIEWS_CREATE_REQUEST'
export const REVIEWS_CREATE_SUCCESS = 'REVIEWS_CREATE_SUCCESS'
export const REVIEWS_CREATE_FAIL = 'REVIEWS_CREATE_FAIL'
export const REVIEWS_CREATE_RESET = 'REVIEWS_CREATE_RESET'
